// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./component/navBar";
import "./globals.css";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${fontSans.variable} font-serif antialiased w-full h-full min-h-screen flex flex-col items-center`}>
        <NavBar />
        <main className="w-full flex-1 flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  );
}